spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/dopaming
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: "likeliontrendithondopaming1teamjwtsecretkey"